server:
  port: 7777

task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50

spring:
  application:
    name: TDEngine-IOT
  datasource:
    tdengine-server:
      driver-class-name: com.taosdata.jdbc.rs.RestfulDriver
      jdbc-url: jdbc:TAOS-RS://192.168.2.250:6041/test?user=root&password=taosdata&timezone=GMT%2b8
      username: root
      password: 123456
      type: com.zaxxer.hikari.HikariDataSource      # Hikari连接池的设置
      minimum-idle: 5                 #最小连接
      maximum-pool-size: 15        #最大连接
      auto-commit: true        #自动提交
      idle-timeout: 30000        #最大空闲时常
      pool-name: TDenginePool        #连接池名
      max-lifetime: 1800000        #最大生命周期
      connection-timeout: 30000        #连接超时时间
      connection-test-query: show tables
    oracle-server:
      #driver-class-name: com.mysql.cj.jdbc.Driver
      #jdbc-url: jdbc:mysql://47.92.104.113:3306/tsdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&allowMultiQueries=true
      #username: root
      #password: 2ZQINmZ0YSiVgnlPMnKx
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbc-url: jdbc:oracle:thin:@192.168.2.230:1521:orcl
      username: IOT_COLLECTOR
      password: rootroot
      type: com.zaxxer.hikari.HikariDataSource
      minimum-idle: 5                 #最小连接
      maximum-pool-size: 15        #最大连接
      auto-commit: true        #自动提交
      idle-timeout: 30000        #最大空闲时常
      pool-name: MysqlPool        #连接池名
      max-lifetime: 1800000        #最大生命周期
      connection-timeout: 30000        #连接超时时间
  opc-ua:
    url: opc.tcp://localhost:49320
    requestedPublishingInterval: 1000.0
    samplingInterval: 1000.0
    queueSize: 1
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 2048MB
  redis:
    #数据库索引
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    #连接超时时间
    timeout: 5000
#mybatis
mybatis:
  type-aliases-package: com.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl     #打印sql
    call-setters-on-nulls: true  #设置查询字段为空时，也返回该字段
    map-underscore-to-camel-case: true
